
services:
  db:
    image: mariadb
    restart: always
    env_file:
      - db.env
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - db.env
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
  flaskapp:
    build: ./backend
    restart: always
    env_file:
      - db.env
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - ./backend:/app  # 確保本地代碼映射到容器中
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://root:example@db/social_platform

  redis:
    image: redis
    restart: always
    depends_on:
      - db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  vue-frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - ./my-nginx-config:/etc/nginx/conf.d

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "D:\\USCC\\Social_Platform\\db_data"
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "D:\\USCC\\Social_Platform\\redis_data"
  static_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "D:\\USCC\\Social_Platform\\backend_static_volume"
